sbomType: Product SBOM
include:
  - path: Library/CMSIS
  - path: Library/Device
  - path: Library/StdDriver
exclude:
  - path: Document/
  - path: SampleCode/
  - path: Library/Device/Nuvoton/M030G/Source/GCC/_syscalls.c
  - path: Library/Device/Nuvoton/M030G/Source/GCC/semihosting.h
